repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable tag
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # Use the latest stable tag
    hooks:
      - id: isort
        args: ["--profile", "black"] # or your preferred profile
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14 # Use the latest stable tag
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"] # auto-fix and fail on any fix
