services:
  backend:
    build: .
    command: conda run -n app_env uvicorn main_fastapi:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  frontend:
    build: .
    command: conda run -n app_env streamlit run main_streamlit.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
